dependencies:
  - name: postgresql
    version: 6.5.3
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: 9.5.3
    repository: https://kubernetes-charts.storage.googleapis.com/
