version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  yolov3:
    lang: dockerfile
    handler: ./yolov3
    image: yolov3:latest
  recognition-web:
    lang: node10-express
    handler: ./web
    image: recognition-web:lastest
    labels:
      com.openfaas.scale.zero: false
