version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  yolov3:
    lang: dockerfile
    handler: ./yolov3
    image: localhost:32000/yolov3:latest
  recognition-web:
    lang: dockerfile
    handler: ./web
    image: localhost:32000/recognition-web:latest
    labels:
      com.openfaas.scale.zero: false
  thumbnail:
    lang: dockerfile
    handler: ./thumbnail
    image: localhost:32000/thumbnail:latest
  albums:
    lang: node10-express
    handler: ./albums
    image: localhost:32000/albums:latest
  photos:
    lang: node10-express
    handler: ./photos
    image: localhost:32000/photos:latest
  storage:
    lang: node10-express
    handler: ./storage
    image: localhost:32000/storage:latest

