version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  yolov3:
    lang: dockerfile
    handler: ./yolov3
    image: mcreng/yolov3:latest
  recognition-web:
    lang: node10-express:latest
    handler: ./web
    image: dipsywong98/recognition-web:lastest
    labels:
      com.openfaas.scale.zero: false
