version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  yolov3:
    lang: dockerfile
    handler: ./yolov3
    image: localhost:32000/yolov3:latest
  recognition-web:
    lang: dockerfile
    handler: ./web
    image: localhost:32000/recognition-web:latest
    labels:
      com.openfaas.scale.zero: false
  thumbnail:
    lang: node
    handler: ./thumbnail
    image: localhost:32000/thumbnail:latest
